/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechniquesRouteImport } from './routes/techniques'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TechniquesRoute = TechniquesRouteImport.update({
  id: '/techniques',
  path: '/techniques',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/projets': typeof ProjetsRoute
  '/services': typeof ServicesRoute
  '/techniques': typeof TechniquesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/projets': typeof ProjetsRoute
  '/services': typeof ServicesRoute
  '/techniques': typeof TechniquesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/projets': typeof ProjetsRoute
  '/services': typeof ServicesRoute
  '/techniques': typeof TechniquesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/contact' | '/partenaires' | '/projets' | '/services' | '/techniques'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/contact' | '/partenaires' | '/projets' | '/services' | '/techniques'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/partenaires'
    | '/projets'
    | '/services'
    | '/techniques'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PartenairesRoute: typeof PartenairesRoute
  ProjetsRoute: typeof ProjetsRoute
  ServicesRoute: typeof ServicesRoute
  TechniquesRoute: typeof TechniquesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/techniques': {
      id: '/techniques'
      path: '/techniques'
      fullPath: '/techniques'
      preLoaderRoute: typeof TechniquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PartenairesRoute: PartenairesRoute,
  ProjetsRoute: ProjetsRoute,
  ServicesRoute: ServicesRoute,
  TechniquesRoute: TechniquesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
